// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5axebJHIz9t-bIjiEDVmCzOnvJeOVk3E',
    appId: '1:168345327273:web:2cb5f58cbe48d01dd13bb8',
    messagingSenderId: '168345327273',
    projectId: 'brand-factory-89120',
    authDomain: 'brand-factory-89120.firebaseapp.com',
    databaseURL: 'https://brand-factory-89120-default-rtdb.firebaseio.com',
    storageBucket: 'brand-factory-89120.firebasestorage.app',
    measurementId: 'G-3EDBXE1V7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi9yRkl33D801O40iTtKbmnk8glzC5_Bk',
    appId: '1:168345327273:android:2926abb347a54e1fd13bb8',
    messagingSenderId: '168345327273',
    projectId: 'brand-factory-89120',
    databaseURL: 'https://brand-factory-89120-default-rtdb.firebaseio.com',
    storageBucket: 'brand-factory-89120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBDk_gQ6G7Hv-7Syv9rwFAA5vTp8TLXw',
    appId: '1:168345327273:ios:e477cb0df962c68cd13bb8',
    messagingSenderId: '168345327273',
    projectId: 'brand-factory-89120',
    databaseURL: 'https://brand-factory-89120-default-rtdb.firebaseio.com',
    storageBucket: 'brand-factory-89120.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceWithProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBDk_gQ6G7Hv-7Syv9rwFAA5vTp8TLXw',
    appId: '1:168345327273:ios:e477cb0df962c68cd13bb8',
    messagingSenderId: '168345327273',
    projectId: 'brand-factory-89120',
    databaseURL: 'https://brand-factory-89120-default-rtdb.firebaseio.com',
    storageBucket: 'brand-factory-89120.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceWithProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5axebJHIz9t-bIjiEDVmCzOnvJeOVk3E',
    appId: '1:168345327273:web:946b186ec34273b6d13bb8',
    messagingSenderId: '168345327273',
    projectId: 'brand-factory-89120',
    authDomain: 'brand-factory-89120.firebaseapp.com',
    databaseURL: 'https://brand-factory-89120-default-rtdb.firebaseio.com',
    storageBucket: 'brand-factory-89120.firebasestorage.app',
    measurementId: 'G-T3XPGWMLJL',
  );
}
